In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

## numpy的concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1, arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

## pd的concatenate

In [8]:
s1 = Series([1,2,3], index=['X', 'Y', 'Z'])

In [9]:
s2 = Series([4,5],index=['A', 'B'])

In [10]:
s1

X    1
Y    2
Z    3
dtype: int64

In [11]:
s2

A    4
B    5
dtype: int64

In [13]:
pd.concat([s1, s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2], axis=1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

## dataframe的concatenate

In [19]:
df1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])

In [20]:
df1

X         Y         Z
0  1.804485  0.572369 -0.507315
1  2.943154  1.553735 -0.566392
2 -0.757869  1.672175 -1.633355
3  0.780971 -2.223730 -1.855050

In [21]:
df2 = DataFrame(np.random.randn(3,3), columns=['X', 'Y','A'])

In [22]:
df2

X         Y         A
0 -1.925779 -0.507399 -1.279667
1  0.903943 -0.137867  1.285866
2  0.543766 -0.934930 -1.438457

In [24]:
pd.concat([df1,df2])

X         Y         Z         A
0  1.804485  0.572369 -0.507315       NaN
1  2.943154  1.553735 -0.566392       NaN
2 -0.757869  1.672175 -1.633355       NaN
3  0.780971 -2.223730 -1.855050       NaN
0 -1.925779 -0.507399       NaN -1.279667
1  0.903943 -0.137867       NaN  1.285866
2  0.543766 -0.934930       NaN -1.438457

# Combine

In [34]:
s1 = Series([2, np.nan, 4, np.nan], index=['A', 'B', 'C', 'D'])

In [35]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [36]:
s2 = Series([1,2,3,4], index=['A', 'B', 'C', 'D'])

In [37]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [38]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [39]:
df1 = DataFrame({
    'X':[1,np.nan, 3,np.nan],
    'Y':[5, np.nan, 7, np.nan],
    'Z':[9, np.nan, 11, np.nan]
})

In [40]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [41]:
df2 = DataFrame({
    'Z':[np.nan, 10,np.nan, 12],
    'A':[1,2,3,4]
})

In [42]:
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [43]:
df1.combine_first(df2)

A    X    Y     Z
0  1  1.0  5.0   9.0
1  2  NaN  NaN  10.0
2  3  3.0  7.0  11.0
3  4  NaN  NaN  12.0