In [1]:
import numpy as np

# 比较narray和list的性能

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
my_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.1 ms, sys: 21.4 ms, total: 38.5 ms
Wall time: 37.8 ms


In [7]:
%time my_arr2 = my_arr * 2

CPU times: user 2.71 ms, sys: 2.15 ms, total: 4.85 ms
Wall time: 2.98 ms


In [8]:
%time my_list2 = [x * 2 for x in my_list]

CPU times: user 55 ms, sys: 17.9 ms, total: 72.9 ms
Wall time: 72 ms


# np.random.rand

In [9]:
np.random.rand()

0.48489330872101555

In [10]:
np.random.rand(4,2)

array([[0.47405912, 0.89069189],
       [0.35637249, 0.57710879],
       [0.30824944, 0.35135509],
       [0.95156952, 0.63106061]])

In [11]:
np.random.rand(4,3,2)

array([[[4.20307044e-02, 9.15186525e-01],
        [8.34902803e-01, 1.75238310e-01],
        [5.86683677e-01, 8.00451549e-01]],

       [[9.94750771e-01, 8.06755565e-01],
        [8.84645636e-01, 3.93916797e-01],
        [6.96701398e-01, 4.98652016e-01]],

       [[7.68889799e-04, 9.34031631e-01],
        [3.51622189e-01, 1.91108319e-01],
        [2.78374407e-01, 1.43419632e-01]],

       [[8.55477276e-01, 9.24521442e-01],
        [3.64197963e-01, 4.78799158e-01],
        [4.67155165e-01, 9.45753700e-01]]])

# np.random.randn

In [12]:
np.random.randn()

-0.616155754351755

In [22]:
data = np.random.randn(2,4)

In [23]:
data.shape

(2, 4)

In [24]:
data.dtype

dtype('float64')

# numpy.random.randint

In [15]:
np.random.randint(1, size=5)

array([0, 0, 0, 0, 0])

In [16]:
np.random.randint(1,5)

1

In [18]:
np.random.randint(1,6)

1

In [19]:
np.random.randint(1,7)

5

In [20]:
np.random.randint(1,8)

4

In [21]:
np.random.randint(-5,5, size=(2,3))

array([[ 3, -1,  4],
       [-2, -3,  4]])

# ndarray创建

In [25]:
data1 = [6,7.5,8,0,1]

In [26]:
arr1 = np.array(data1)

In [27]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [28]:
# 嵌套
data2 = [[1,2,3,4], [5,6,7,8]]

In [29]:
arr2 = np.array(data2)

In [30]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arr2.ndim

2

In [32]:
arr2.shape

(2, 4)

In [33]:
np.empty((2, 3, 2))

array([[[-2.00000000e+000, -1.49457869e-154],
        [ 2.35179017e-314,  2.38459678e-314],
        [ 2.12199579e-314,  4.47032019e-038]],

       [[ 7.79316619e-091,  9.96444597e-047],
        [ 8.41208216e+164,  9.59081510e-043],
        [ 3.99910963e+252,  8.34405083e-309]]])

# 基本的索引和切片

In [34]:
arr = np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

5

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12

In [39]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
arr_slice = arr[5:8]

In [41]:
arr_slice

array([12, 12, 12])

In [42]:
arr_slice[1] = 1234

In [43]:
arr_slice

array([  12, 1234,   12])

In [44]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [45]:
arr_slice[:] = 64

In [46]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# 布尔索引模式

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [48]:
data = np.random.randn(7,4)

In [49]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [50]:
data

array([[-0.89996307,  0.97168147, -1.02364667,  0.15380432],
       [ 0.90614626,  0.87932366,  0.45714149, -0.83117882],
       [ 0.65336118, -1.16633208, -0.97387672,  1.94825322],
       [ 0.192677  , -0.15049339,  0.00600018, -0.11992264],
       [-1.35840794,  3.00439996,  0.28121086,  0.02133128],
       [ 1.06696269, -0.66239783,  3.25467564,  1.95533297],
       [ 0.71109537, -0.42977012, -1.26952603,  1.5150302 ]])

In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [52]:
data[names == 'Bob']

array([[-0.89996307,  0.97168147, -1.02364667,  0.15380432],
       [ 0.192677  , -0.15049339,  0.00600018, -0.11992264]])

In [53]:
data[names == 'Bob', 2:]

array([[-1.02364667,  0.15380432],
       [ 0.00600018, -0.11992264]])

In [54]:
data[names == 'Bob', 3]

array([ 0.15380432, -0.11992264])

In [55]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [56]:
data[names != 'Bob']

array([[ 0.90614626,  0.87932366,  0.45714149, -0.83117882],
       [ 0.65336118, -1.16633208, -0.97387672,  1.94825322],
       [-1.35840794,  3.00439996,  0.28121086,  0.02133128],
       [ 1.06696269, -0.66239783,  3.25467564,  1.95533297],
       [ 0.71109537, -0.42977012, -1.26952603,  1.5150302 ]])

In [57]:
data[data < 0] = 0

In [58]:
data

array([[0.        , 0.97168147, 0.        , 0.15380432],
       [0.90614626, 0.87932366, 0.45714149, 0.        ],
       [0.65336118, 0.        , 0.        , 1.94825322],
       [0.192677  , 0.        , 0.00600018, 0.        ],
       [0.        , 3.00439996, 0.28121086, 0.02133128],
       [1.06696269, 0.        , 3.25467564, 1.95533297],
       [0.71109537, 0.        , 0.        , 1.5150302 ]])

In [59]:
data[names != 'Joe'] = 7

In [60]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.90614626, 0.87932366, 0.45714149, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.06696269, 0.        , 3.25467564, 1.95533297],
       [0.71109537, 0.        , 0.        , 1.5150302 ]])

# 花式索引

In [61]:
arr = np.arange(32)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [63]:
arr = arr.reshape(8,4)

In [64]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [65]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [66]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [67]:
arr[[0, 3, 1, 2]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 将条件逻辑表述为数组运算

In [68]:
arr = np.random.randn(4,4)

In [69]:
arr

array([[-1.04076933,  1.65072087,  1.35315979, -1.01002881],
       [-0.59603931,  0.41339379, -1.0842827 , -0.25534604],
       [-0.10819075,  1.04399426,  0.1254208 ,  1.11814952],
       [-0.45845036,  0.74454226, -1.44727425, -1.39496056]])

In [70]:
arr > 0

array([[False,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [71]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2,  2,  2,  2],
       [-2,  2, -2, -2]])

In [72]:
np.where(arr > 0, 2, arr)

array([[-1.04076933,  2.        ,  2.        , -1.01002881],
       [-0.59603931,  2.        , -1.0842827 , -0.25534604],
       [-0.10819075,  2.        ,  2.        ,  2.        ],
       [-0.45845036,  2.        , -1.44727425, -1.39496056]])

# 数学和统计方法

In [73]:
arr = np.random.randn(5,4)

In [74]:
arr

array([[-0.47086541, -0.83168693,  0.66157721, -1.00126159],
       [ 0.3106339 , -0.34892019, -1.18924491, -0.30498826],
       [ 0.94847241,  0.41677276,  0.63175045, -0.07976668],
       [-0.39441888,  1.07894831,  1.55812708,  0.90527184],
       [ 1.15637308,  0.39658952, -2.16051669, -0.56347671]])

In [75]:
arr.mean()

0.03596851519595123

In [76]:
arr.sum()

0.7193703039190246

In [77]:
arr.mean(axis=1)

array([-0.41055918, -0.38312986,  0.47930723,  0.78698209, -0.2927577 ])

In [78]:
arr.mean(axis=0)

array([ 0.31003902,  0.14234069, -0.09966137, -0.20884428])

# 用于布尔型数组的方法

In [79]:
arr = np.random.randn(100)

In [80]:
arr

array([ 0.52758702, -0.62138907, -0.58471255,  2.43944326,  0.60404854,
        0.48307624, -2.39175152,  0.63785609,  0.41555723, -1.86412478,
        0.9198044 , -0.47422535,  0.45240284, -0.23085321, -0.72609217,
       -0.90235707, -0.7027114 , -1.18633358, -0.11619865, -1.49283893,
       -0.61676595,  0.57596143, -1.03909975,  0.41845912, -2.07488675,
        0.03102195, -1.22065409, -0.96795215, -1.98854273,  0.63587713,
       -0.61200093,  0.4776013 ,  0.97953411,  0.10164334, -0.76924091,
        1.48619283, -1.9277447 ,  0.69346234,  0.8702187 ,  0.03046277,
        0.77810698,  0.11296083,  0.84361673,  0.50274339, -0.41374669,
       -0.96016837, -0.47045744, -0.52804331, -1.43311908, -0.13788543,
       -0.53638447,  0.34045306,  0.65764497, -1.00211332, -0.09366074,
        0.31576205, -1.09879313, -1.22156296, -0.47223966, -0.29473661,
       -0.82517057,  0.31951025,  1.34472079, -0.22917516, -0.05720734,
        0.14731382,  0.80649591,  0.0701663 , -1.22735991, -1.18

In [81]:
(arr > 0).sum()

47

In [82]:
bools = np.array([False, True, True, False])

In [83]:
bools.any()

True

In [84]:
bools.all()

False