In [1]:
import numpy
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3], index=['a','b','c','d'])

In [7]:
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [8]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [9]:
obj3 = pd.Series(sdata)

In [10]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [11]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [12]:
obj4 = pd.Series(sdata, index=states)

In [13]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [15]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [16]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [20]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [23]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [24]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [25]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [26]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [27]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [28]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four','five', 'six'])

In [29]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [33]:
import numpy as np
np.arange(6.)

array([0., 1., 2., 3., 4., 5.])

In [34]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [35]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [36]:
frame2['debt'] = 16.5

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [39]:
import numpy as np
frame2.debt = np.arange(6.)

In [40]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [41]:
frame2['eastern'] = frame2.state == 'Ohio'

In [42]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False

In [43]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
frame3 = pd.DataFrame(pop)

In [45]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [46]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [47]:
frame3.index.name = 'year'

In [48]:
frame3.columns.name = 'state'

In [49]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [50]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [51]:
frame2.values

array([[2000, 'Ohio', 1.5, 0.0, True],
       [2001, 'Ohio', 1.7, 1.0, True],
       [2002, 'Ohio', 3.6, 2.0, True],
       [2001, 'Nevada', 2.4, 3.0, False],
       [2002, 'Nevada', 2.9, 4.0, False],
       [2003, 'Nevada', 3.2, 5.0, False]], dtype=object)

In [52]:
type(frame2.values)

numpy.ndarray

# 索引对象

In [57]:
obj = pd.DataFrame(range(3), index=['a','b','c'])

In [58]:
obj

0
a  0
b  1
c  2

In [59]:
index = obj.index

In [60]:
index

Index(['a', 'b', 'c'], dtype='object')

In [61]:
index[1:]

Index(['b', 'c'], dtype='object')

In [62]:
index[1] = 'd'

TypeError: Index does not support mutable operations

# 重新索引

In [63]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [64]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [65]:
# obj.reindex，不会影响obj的数据
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [66]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [67]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [68]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [69]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [70]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [71]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [72]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [73]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [74]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [75]:
states = ['Texas', 'Utah', 'California']

In [76]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [77]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

# 整数索引

In [78]:
ser = pd.Series(np.arange(3.))

In [79]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [80]:
ser[:1]

0    0.0
dtype: float64

In [81]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [82]:
ser[-1]

KeyError: -1

In [83]:
ser.iloc[:1]

0    0.0
dtype: float64

# 排序和排名

In [84]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [85]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64